### ISSUE TITLE
Premissa do jogo

### ISSUE THREAD

**Issue by edupferraz** [Lorum-Gaming/God-Between-Us#1]

**Comment by gabiicosta** [comment]
Junte-se a Max em sua jornada de vida, enfrente desafios, tome decisões importantes e experimente o crescimento e o amadurecimento ao longo do tempo. Conheça personagens emblemáticos e explore mundos fascinantes. Jogue agora e sinta a emoção de viver a vida de Max, da Infância ao legado!"

**Comment by edupferraz** [comment]
Essas informações estão disponíveis no https://github.com/Lorum-Gaming/God-Between-Us
