### ISSUE TITLE
Criar assets personalizados

### ISSUE THREAD

**Issue by edupferraz** [Lorum-Gaming/God-Between-Us#40]
Esta tarefa é opcional. Além disso pode ser desmembrada, de acordo com o volume de trabalho escolhido pela equipe, em outras: 

- [x] Tiles
- [x] Sprites
- [x] Sons de efeito
- [x] Músicas

Depende de #20, #22 e #24

**Comment by gabiicosta** [comment]
Itens estão nos assets no github
